/**
 * PARIS API
 * The PARIS API is based on a REST achitecture, and is using JSON as data format.<br/>PARIS API is Stateless, the server does not store any state about the client session on the server side. Statelessness ensures that each service consumer request can be treated independently by the service.<br/>Authentication against the API is done using a combination of Basic Authentication and Token based authentication or API-Keys.<br/><br/>©2021 NORIA AS. All Rights Reserved. PARIS is a trademark of <a href=\"http://noria.no/\" target=\"_blank\">NORIA AS</a>.
 *
 * The version of the OpenAPI document: 4.7-202112021325
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ElectronicRemittance } from './electronicRemittance';
import { AuthorizationRule } from './authorizationRule';
import { ClaimSettlement } from './claimSettlement';
import { SimplePerson } from './simplePerson';

export interface ClaimPayment {
  created?: string;
  createdBy?: string;
  id?: string;
  documentNumber?: number;
  validFrom: string;
  documentDate: string;
  exchangeDate?: string;
  _function: ClaimPayment.FunctionEnum;
  reset?: boolean;
  dueDate: string;
  currency: string;
  paymentCode?: number;
  accountingGroup: ClaimPayment.AccountingGroupEnum;
  paymentReceiver: SimplePerson;
  legalReceiver: SimplePerson;
  bankAccountNumber?: string;
  personalLedgerText?: string;
  personalLedgerAmount?: number;
  feeAmount?: number;
  balance: number;
  note?: string;
  generalLedgerAccount?: number;
  generalCurrency?: string;
  generalAmount?: number;
  taxModel?: ClaimPayment.TaxModelEnum;
  messageToElectronicRemittance?: string;
  externalDocumentId?: string;
  transferAccounting?: boolean;
  toBeSignedBy1?: string;
  signedBy1?: string;
  signedDate1?: string;
  toBeSignedBy2?: string;
  signedBy2?: string;
  signedDate2?: string;
  claimSettlements?: Array<ClaimSettlement>;
  electronicRemittance?: ElectronicRemittance;
  electronicRemitted?: boolean;
  paymentType?: ClaimPayment.PaymentTypeEnum;
  ingoingInvoiceId?: number;
  bordereauText?: string;
  payment?: boolean;
  authorizationRule?: AuthorizationRule;
  canChangeAuthorizationRule?: boolean;
  canModify?: boolean;
  canRelease?: boolean;
  status?: ClaimPayment.StatusEnum;
}
export namespace ClaimPayment {
  export type FunctionEnum =
    | 'CLAIM_BORDEREAU_C'
    | 'ESTIMATE_E'
    | 'GENERAL_LEDGER_G'
    | 'INTERNAL_I'
    | 'PAYMENT_P'
    | 'GL_TRANS_WCLMB_Q'
    | 'PAYMENT_WCLMBO_R'
    | 'SETTLE_S'
    | 'FX_X';
  export const FunctionEnum = {
    ClaimBordereauC: 'CLAIM_BORDEREAU_C' as FunctionEnum,
    EstimateE: 'ESTIMATE_E' as FunctionEnum,
    GeneralLedgerG: 'GENERAL_LEDGER_G' as FunctionEnum,
    InternalI: 'INTERNAL_I' as FunctionEnum,
    PaymentP: 'PAYMENT_P' as FunctionEnum,
    GlTransWclmbQ: 'GL_TRANS_WCLMB_Q' as FunctionEnum,
    PaymentWclmboR: 'PAYMENT_WCLMBO_R' as FunctionEnum,
    SettleS: 'SETTLE_S' as FunctionEnum,
    FxX: 'FX_X' as FunctionEnum,
  };
  export type AccountingGroupEnum =
    | 'DIRECT_1'
    | 'RECEIVED_2'
    | 'CEDED_3'
    | 'CLAIM_ACCOUNTS_4'
    | 'AGENTS_7'
    | 'INTERIMS_9'
    | 'UNSPECIFIED_99';
  export const AccountingGroupEnum = {
    Direct1: 'DIRECT_1' as AccountingGroupEnum,
    Received2: 'RECEIVED_2' as AccountingGroupEnum,
    Ceded3: 'CEDED_3' as AccountingGroupEnum,
    ClaimAccounts4: 'CLAIM_ACCOUNTS_4' as AccountingGroupEnum,
    Agents7: 'AGENTS_7' as AccountingGroupEnum,
    Interims9: 'INTERIMS_9' as AccountingGroupEnum,
    Unspecified99: 'UNSPECIFIED_99' as AccountingGroupEnum,
  };
  export type TaxModelEnum =
    | 'NONE_0'
    | 'NORW_MVA_1'
    | 'SWEDISH_TAX_2'
    | 'FINNISH_TAX_3'
    | 'GB_TAX_4'
    | 'US_TAX_5'
    | 'BELGIUM_TAX_6';
  export const TaxModelEnum = {
    None0: 'NONE_0' as TaxModelEnum,
    NorwMva1: 'NORW_MVA_1' as TaxModelEnum,
    SwedishTax2: 'SWEDISH_TAX_2' as TaxModelEnum,
    FinnishTax3: 'FINNISH_TAX_3' as TaxModelEnum,
    GbTax4: 'GB_TAX_4' as TaxModelEnum,
    UsTax5: 'US_TAX_5' as TaxModelEnum,
    BelgiumTax6: 'BELGIUM_TAX_6' as TaxModelEnum,
  };
  export type PaymentTypeEnum =
    | 'PERSONAL_LEDGER_WITH_REG'
    | 'PERSONAL_LEDGER'
    | 'GENERAL_LEDGER'
    | 'PERSONAL_LEDGER_BROKER_WITH_REG';
  export const PaymentTypeEnum = {
    PersonalLedgerWithReg: 'PERSONAL_LEDGER_WITH_REG' as PaymentTypeEnum,
    PersonalLedger: 'PERSONAL_LEDGER' as PaymentTypeEnum,
    GeneralLedger: 'GENERAL_LEDGER' as PaymentTypeEnum,
    PersonalLedgerBrokerWithReg:
      'PERSONAL_LEDGER_BROKER_WITH_REG' as PaymentTypeEnum,
  };
  export type StatusEnum =
    | 'TAKEN_10'
    | 'NOT_USED_11'
    | 'DRAFT_12'
    | 'HOLD_13'
    | 'RELEASE_14'
    | 'WAIT_FOR_SIGN_15'
    | 'DISM_SIGNATURE_16'
    | 'CTRL_17'
    | 'WAITUNTIL_19'
    | 'ORDERED_SPREAD_20'
    | 'SPREAD_PROCESS_21'
    | 'SPREAD_UNCOMP_29'
    | 'PERSLEDGER_REA_30'
    | 'PL_PROCECESS_31'
    | 'PL_UNCOMPLETE_39'
    | 'BORDREADY_40'
    | 'BORD_PROCESS_41'
    | 'BORD_UNCOMPLETE_49'
    | 'GL_PRODREADY_50'
    | 'GL_PROCESS_51'
    | 'GL_RUN_1_52'
    | 'GL_DIFFLIST_53'
    | 'GL_UNCOMPLETE_54'
    | 'READY_FOR_EXPOR_55'
    | 'EXPORT_IN_PROGR_56'
    | 'EXP_NO_ACCLINE_58'
    | 'EXP_UNCOMPLETE_59'
    | 'ALL_DONE_60'
    | 'ALL_DONE_MANUAL_61'
    | 'ONHOLD_9';
  export const StatusEnum = {
    Taken10: 'TAKEN_10' as StatusEnum,
    NotUsed11: 'NOT_USED_11' as StatusEnum,
    Draft12: 'DRAFT_12' as StatusEnum,
    Hold13: 'HOLD_13' as StatusEnum,
    Release14: 'RELEASE_14' as StatusEnum,
    WaitForSign15: 'WAIT_FOR_SIGN_15' as StatusEnum,
    DismSignature16: 'DISM_SIGNATURE_16' as StatusEnum,
    Ctrl17: 'CTRL_17' as StatusEnum,
    Waituntil19: 'WAITUNTIL_19' as StatusEnum,
    OrderedSpread20: 'ORDERED_SPREAD_20' as StatusEnum,
    SpreadProcess21: 'SPREAD_PROCESS_21' as StatusEnum,
    SpreadUncomp29: 'SPREAD_UNCOMP_29' as StatusEnum,
    PersledgerRea30: 'PERSLEDGER_REA_30' as StatusEnum,
    PlProcecess31: 'PL_PROCECESS_31' as StatusEnum,
    PlUncomplete39: 'PL_UNCOMPLETE_39' as StatusEnum,
    Bordready40: 'BORDREADY_40' as StatusEnum,
    BordProcess41: 'BORD_PROCESS_41' as StatusEnum,
    BordUncomplete49: 'BORD_UNCOMPLETE_49' as StatusEnum,
    GlProdready50: 'GL_PRODREADY_50' as StatusEnum,
    GlProcess51: 'GL_PROCESS_51' as StatusEnum,
    GlRun152: 'GL_RUN_1_52' as StatusEnum,
    GlDifflist53: 'GL_DIFFLIST_53' as StatusEnum,
    GlUncomplete54: 'GL_UNCOMPLETE_54' as StatusEnum,
    ReadyForExpor55: 'READY_FOR_EXPOR_55' as StatusEnum,
    ExportInProgr56: 'EXPORT_IN_PROGR_56' as StatusEnum,
    ExpNoAccline58: 'EXP_NO_ACCLINE_58' as StatusEnum,
    ExpUncomplete59: 'EXP_UNCOMPLETE_59' as StatusEnum,
    AllDone60: 'ALL_DONE_60' as StatusEnum,
    AllDoneManual61: 'ALL_DONE_MANUAL_61' as StatusEnum,
    Onhold9: 'ONHOLD_9' as StatusEnum,
  };
}
