/**
 * PARIS API
 * The PARIS API is based on a REST achitecture, and is using JSON as data format.<br/>PARIS API is Stateless, the server does not store any state about the client session on the server side. Statelessness ensures that each service consumer request can be treated independently by the service.<br/>Authentication against the API is done using a combination of Basic Authentication and Token based authentication or API-Keys.<br/><br/>©2021 NORIA AS. All Rights Reserved. PARIS is a trademark of <a href=\"http://noria.no/\" target=\"_blank\">NORIA AS</a>.
 *
 * The version of the OpenAPI document: 4.7-202112021325
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClaimEvent } from './claimEvent';
import { ClaimObject } from './claimObject';
import { ClaimOperations } from './claimOperations';
import { CoverageInformation } from './coverageInformation';
import { SimpleInsuredObject } from './simpleInsuredObject';
import { ClaimTotals } from './claimTotals';
import { Responsible } from './responsible';
import { WorkPlace } from './workPlace';
import { SimplePerson } from './simplePerson';

export interface Claim {
  created?: string;
  createdBy?: string;
  lastUpdated?: string;
  lastUpdatedBy?: string;
  id?: string;
  coverageInformation?: CoverageInformation;
  coverageId: string;
  status?: Claim.StatusEnum;
  claimEvent: ClaimEvent;
  date?: string;
  reportedDate?: string;
  handler?: string;
  code?: string;
  codeDate?: string;
  lastTreatmentDate?: string;
  office?: number;
  totals?: ClaimTotals;
  operations?: ClaimOperations;
  claimant?: SimplePerson;
  insured?: SimplePerson;
  place?: number;
  numberOfDays?: number;
  degreeOfDisablement?: number;
  occupationalDegreeOfDisablement?: number;
  limitCurrency?: string;
  limitAmount?: number;
  insuredAmount?: number;
  looseBonus?: boolean;
  hour?: number;
  common?: boolean;
  areaCode?: string;
  fromAreaCode?: string;
  toAreaCode?: string;
  taxRegion?: string;
  areaDescription?: string;
  tauCode?: number;
  tauText?: string;
  liabilityCode?: number;
  liabilityText?: string;
  cargoType?: string;
  transportType?: number;
  reference?: string;
  text?: string;
  internalNote?: string;
  mainCasualty?: string;
  detailCasualty?: string;
  nonmarineClaimEffect?: string;
  nonmarineClaimCause?: string;
  generalClaimCause?: string;
  totalLoss?: boolean;
  automaticSettlement?: boolean;
  closeDate?: string;
  nextActionDate?: string;
  longDescription?: string;
  externalClaimId?: string;
  calculateInterest?: boolean;
  workPlace?: WorkPlace;
  lossAdjusterDate?: string;
  numberOfTreatment1?: number;
  numberOfTreatment2?: number;
  timeBarNote?: string;
  largeClaimGroup?: boolean;
  object?: SimpleInsuredObject;
  geoDescription?: string;
  regress?: Claim.RegressEnum;
  regressDate?: string;
  regressBy?: string;
  regressCurrency?: string;
  regressAmount?: number;
  regressText?: string;
  claimObjects?: Array<ClaimObject>;
  exchangeDateForAutoDeductibles?: string;
  pilotOnBoard?: Claim.PilotOnBoardEnum;
  codeDescription?: string;
  codeTreatmentDate?: string;
  adjuster?: string;
  externalAdjuster?: boolean;
  onOrOffshoreCode?: Claim.OnOrOffshoreCodeEnum;
  amountNoDecimals?: number;
  insuredCurrency?: string;
  energyAssuredsShare?: number;
  energyLossLocationOnObject?: string;
  energyLossObjectFunction?: string;
  energyLossDamageOnItem?: string;
  energyClaimCauseCode?: string;
  categoryType?: Claim.CategoryTypeEnum;
  totalLossType?: Claim.TotalLossTypeEnum;
  potentialRecovery?: Claim.PotentialRecoveryEnum;
  claimRecoveryCode?: number;
  potentialRecoveryCurrency?: string;
  potentialRecoveryAmount?: number;
  potentialRecoveryInternalNote?: string;
  recoveryAchieved?: boolean;
  recoveryAchievedCurrency?: string;
  recoveryAchievedAmount?: number;
  recoveryAchievedDate?: string;
  recoveryReminderDate?: string;
  recoveryAchievedSignature?: string;
  recoveryAchievedInternalNote?: string;
  internalConflict?: boolean;
  timeBarDate?: string;
  objectName?: string;
  startOfRisk?: string;
  meansOfTransport?: string;
  fromPort?: string;
  placeOfReceipt?: string;
  portOfLoading?: string;
  portOfDischarge?: string;
  placeOfDelivery?: string;
  countryOfDischarge?: string;
  claimId?: number;
  responsibles?: Array<Responsible>;
}
export namespace Claim {
  export type StatusEnum =
    | 'ACTIVE_1'
    | 'CLM_CLOSED_2'
    | 'CLM_REOPEN_3'
    | 'CLM_RCLOSED_4'
    | 'DELETED_9';
  export const StatusEnum = {
    Active1: 'ACTIVE_1' as StatusEnum,
    ClmClosed2: 'CLM_CLOSED_2' as StatusEnum,
    ClmReopen3: 'CLM_REOPEN_3' as StatusEnum,
    ClmRclosed4: 'CLM_RCLOSED_4' as StatusEnum,
    Deleted9: 'DELETED_9' as StatusEnum,
  };
  export type RegressEnum =
    | 'NOT_POSSIBLE_1'
    | 'POSSIBLE_2'
    | 'TREATEMENT_3'
    | 'FINISHED_4'
    | 'ANSVAR_ERKJENT_5'
    | 'DELVIS_BETALT_6'
    | 'BET_AVSLUTTET_7'
    | 'NOT_TREATED_8';
  export const RegressEnum = {
    NotPossible1: 'NOT_POSSIBLE_1' as RegressEnum,
    Possible2: 'POSSIBLE_2' as RegressEnum,
    Treatement3: 'TREATEMENT_3' as RegressEnum,
    Finished4: 'FINISHED_4' as RegressEnum,
    AnsvarErkjent5: 'ANSVAR_ERKJENT_5' as RegressEnum,
    DelvisBetalt6: 'DELVIS_BETALT_6' as RegressEnum,
    BetAvsluttet7: 'BET_AVSLUTTET_7' as RegressEnum,
    NotTreated8: 'NOT_TREATED_8' as RegressEnum,
  };
  export type PilotOnBoardEnum = 'NO_N' | 'YES_Y' | 'UNKNOWN_Z';
  export const PilotOnBoardEnum = {
    NoN: 'NO_N' as PilotOnBoardEnum,
    YesY: 'YES_Y' as PilotOnBoardEnum,
    UnknownZ: 'UNKNOWN_Z' as PilotOnBoardEnum,
  };
  export type OnOrOffshoreCodeEnum =
    | 'DOWNSTREAM_1'
    | 'UPSTREAM_2'
    | 'UNSPECIFIED_9';
  export const OnOrOffshoreCodeEnum = {
    Downstream1: 'DOWNSTREAM_1' as OnOrOffshoreCodeEnum,
    Upstream2: 'UPSTREAM_2' as OnOrOffshoreCodeEnum,
    Unspecified9: 'UNSPECIFIED_9' as OnOrOffshoreCodeEnum,
  };
  export type CategoryTypeEnum =
    | 'GENAVERAGE_1'
    | 'GAVR_ABSORPTIO_2'
    | 'ASSUMGENAVR_3'
    | 'SUE__LABOUR_4'
    | 'NONE_Z';
  export const CategoryTypeEnum = {
    Genaverage1: 'GENAVERAGE_1' as CategoryTypeEnum,
    GavrAbsorptio2: 'GAVR_ABSORPTIO_2' as CategoryTypeEnum,
    Assumgenavr3: 'ASSUMGENAVR_3' as CategoryTypeEnum,
    SueLabour4: 'SUE__LABOUR_4' as CategoryTypeEnum,
    NoneZ: 'NONE_Z' as CategoryTypeEnum,
  };
  export type TotalLossTypeEnum = 'UNSPEC_0' | 'ACTUAL_1' | 'CONSTRUCTIVE_2';
  export const TotalLossTypeEnum = {
    Unspec0: 'UNSPEC_0' as TotalLossTypeEnum,
    Actual1: 'ACTUAL_1' as TotalLossTypeEnum,
    Constructive2: 'CONSTRUCTIVE_2' as TotalLossTypeEnum,
  };
  export type PotentialRecoveryEnum = 'NO_N' | 'UNKNOWN_U' | 'YES_Y';
  export const PotentialRecoveryEnum = {
    NoN: 'NO_N' as PotentialRecoveryEnum,
    UnknownU: 'UNKNOWN_U' as PotentialRecoveryEnum,
    YesY: 'YES_Y' as PotentialRecoveryEnum,
  };
}
