/**
 * PARIS API
 * The PARIS API is based on a REST achitecture, and is using JSON as data format.<br/>PARIS API is Stateless, the server does not store any state about the client session on the server side. Statelessness ensures that each service consumer request can be treated independently by the service.<br/>Authentication against the API is done using a combination of Basic Authentication and Token based authentication or API-Keys.<br/><br/>©2021 NORIA AS. All Rights Reserved. PARIS is a trademark of <a href=\"http://noria.no/\" target=\"_blank\">NORIA AS</a>.
 *
 * The version of the OpenAPI document: 4.7-202112021325
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleUser } from './simpleUser';
import { PersonVersion } from './personVersion';
import { SimplePerson } from './simplePerson';

export interface Person {
  id?: number;
  name?: string;
  shortName: string;
  type: Person.TypeEnum;
  status?: Person.StatusEnum;
  stopUse?: boolean;
  invisible?: boolean;
  canModify?: boolean;
  ssn?: string;
  orgNo?: string;
  sex?: Person.SexEnum;
  specification: Person.SpecificationEnum;
  giroType?: Person.GiroTypeEnum;
  giroNumber?: string;
  electronic?: boolean;
  phone?: string;
  mobile?: string;
  email?: string;
  coAddress?: string;
  streetAddress?: string;
  address3?: string;
  address4?: string;
  postal?: string;
  country?: string;
  language: string;
  contactPersonName?: string;
  contactPersonPhone?: string;
  contactPersonMobile?: string;
  contactPersonEmail?: string;
  fax?: string;
  ccEmail?: string;
  alternatePayer?: SimplePerson;
  created?: string;
  createdBy?: string;
  createdByUser?: SimpleUser;
  lastUpdated?: string;
  lastUpdatedBy?: string;
  lastUpdatedByUser?: SimpleUser;
  owner?: string;
  concern?: SimplePerson;
  subType: number;
  leiCode?: string;
  busnDivision?: number;
  busnSection?: number;
  busnClass?: number;
  office?: number;
  agent?: SimplePerson;
  defaultMortgage?: SimplePerson;
  accountingRebate?: boolean;
  version: PersonVersion;
  noteBreakUp?: Person.NoteBreakUpEnum;
  creditDays: number;
  interestCalculation?: boolean;
  daysBetweenPremiumNote: number;
  dueDay: number;
  omitReminder?: boolean;
  omitPremiumNote?: boolean;
  collectFee?: boolean;
  instalmentMethod?: Person.InstalmentMethodEnum;
  noteType?: Person.NoteTypeEnum;
  giroLastUpdated?: string;
  giroLastUpdatedBy?: string;
  noteSort?: Person.NoteSortEnum;
  stopDunning?: Person.StopDunningEnum;
  expiresDate?: string;
  giroAgreement?: Person.GiroAgreementEnum;
  customerIdentificationNumber?: string;
  notifyCustomer?: boolean;
  claimInterest?: boolean;
  hasHistoricSettlement?: boolean;
  crmId?: string;
  mailDistribution?: boolean;
  externalTransfer?: boolean;
  externalId?: string;
  identity?: string;
  smallCraft?: boolean;
  vatNo?: string;
  vatIndicator?: Person.VatIndicatorEnum;
  externalId2?: string;
  defaultCurrency?: string;
  externalRegistrationDate?: string;
  dsfAddressCode?: Person.DsfAddressCodeEnum;
  einvoiceB2C?: Person.EinvoiceB2CEnum;
  einvoiceB2B?: Person.EinvoiceB2BEnum;
  einvoiceB2BType?: string;
  einvoiceB2CReference?: string;
}
export namespace Person {
  export type TypeEnum =
    | 'INSURANCE_COMP_1'
    | 'LAWYER_10'
    | 'AVR_ADJUSTER_11'
    | 'RATING_COMP_12'
    | 'MARITIME_AUTHOR_13'
    | 'INSURANCE_BROKE_2'
    | 'OPPOSITE_PARTY_21'
    | 'CLAIM_RECEIVER_22'
    | 'ONE_TIME_VENDOR_23'
    | 'COVER_3'
    | 'QUOTA_SHTREATY_4'
    | 'CUSTOMER_DIR_5'
    | 'EMPLOYEE_51'
    | 'CREW_52'
    | 'ASSOCIATION_55'
    | 'SALES_AGENT_6'
    | 'AGENTOFFICE_61'
    | 'AGENTEMPLOYEE_62'
    | 'SURVEYOR_7'
    | 'MORTGBANK_8'
    | 'ORGANOFFICE_81'
    | 'ORGEMPLOYEE_82'
    | 'CORRESPONDENT_83'
    | 'REGION_85'
    | 'MORTGOFFICE_86'
    | 'INTERIM_1_88'
    | 'MORTGAGEE_CON_9'
    | 'OWN_RETENTION_91'
    | 'CUTOFF_92'
    | 'OWN_COMM_BR_93'
    | 'TECHNICAL_ADDR_94'
    | 'INTERIM_ACCOUNT_95'
    | 'INGOING_VAT_96'
    | 'OUTGOING_VAT_97'
    | 'INTERIM_2_98'
    | 'OTHER_99';
  export const TypeEnum = {
    InsuranceComp1: 'INSURANCE_COMP_1' as TypeEnum,
    Lawyer10: 'LAWYER_10' as TypeEnum,
    AvrAdjuster11: 'AVR_ADJUSTER_11' as TypeEnum,
    RatingComp12: 'RATING_COMP_12' as TypeEnum,
    MaritimeAuthor13: 'MARITIME_AUTHOR_13' as TypeEnum,
    InsuranceBroke2: 'INSURANCE_BROKE_2' as TypeEnum,
    OppositeParty21: 'OPPOSITE_PARTY_21' as TypeEnum,
    ClaimReceiver22: 'CLAIM_RECEIVER_22' as TypeEnum,
    OneTimeVendor23: 'ONE_TIME_VENDOR_23' as TypeEnum,
    Cover3: 'COVER_3' as TypeEnum,
    QuotaShtreaty4: 'QUOTA_SHTREATY_4' as TypeEnum,
    CustomerDir5: 'CUSTOMER_DIR_5' as TypeEnum,
    Employee51: 'EMPLOYEE_51' as TypeEnum,
    Crew52: 'CREW_52' as TypeEnum,
    Association55: 'ASSOCIATION_55' as TypeEnum,
    SalesAgent6: 'SALES_AGENT_6' as TypeEnum,
    Agentoffice61: 'AGENTOFFICE_61' as TypeEnum,
    Agentemployee62: 'AGENTEMPLOYEE_62' as TypeEnum,
    Surveyor7: 'SURVEYOR_7' as TypeEnum,
    Mortgbank8: 'MORTGBANK_8' as TypeEnum,
    Organoffice81: 'ORGANOFFICE_81' as TypeEnum,
    Orgemployee82: 'ORGEMPLOYEE_82' as TypeEnum,
    Correspondent83: 'CORRESPONDENT_83' as TypeEnum,
    Region85: 'REGION_85' as TypeEnum,
    Mortgoffice86: 'MORTGOFFICE_86' as TypeEnum,
    Interim188: 'INTERIM_1_88' as TypeEnum,
    MortgageeCon9: 'MORTGAGEE_CON_9' as TypeEnum,
    OwnRetention91: 'OWN_RETENTION_91' as TypeEnum,
    Cutoff92: 'CUTOFF_92' as TypeEnum,
    OwnCommBr93: 'OWN_COMM_BR_93' as TypeEnum,
    TechnicalAddr94: 'TECHNICAL_ADDR_94' as TypeEnum,
    InterimAccount95: 'INTERIM_ACCOUNT_95' as TypeEnum,
    IngoingVat96: 'INGOING_VAT_96' as TypeEnum,
    OutgoingVat97: 'OUTGOING_VAT_97' as TypeEnum,
    Interim298: 'INTERIM_2_98' as TypeEnum,
    Other99: 'OTHER_99' as TypeEnum,
  };
  export type StatusEnum =
    | 'NORMAL_0'
    | 'EXPIRED_1'
    | 'DEAD_10'
    | 'CHANGED_COMPANY_2'
    | 'DISMISSED_CLAIM_3'
    | 'DISMISSED_PAYMT_4'
    | 'BANKRUPT_5'
    | 'SLOW_PAYER_6'
    | 'CUTOFF_7'
    | 'PREENTERED_89'
    | 'APPROVED_90'
    | 'LEGAL_RECOVERY_99';
  export const StatusEnum = {
    Normal0: 'NORMAL_0' as StatusEnum,
    Expired1: 'EXPIRED_1' as StatusEnum,
    Dead10: 'DEAD_10' as StatusEnum,
    ChangedCompany2: 'CHANGED_COMPANY_2' as StatusEnum,
    DismissedClaim3: 'DISMISSED_CLAIM_3' as StatusEnum,
    DismissedPaymt4: 'DISMISSED_PAYMT_4' as StatusEnum,
    Bankrupt5: 'BANKRUPT_5' as StatusEnum,
    SlowPayer6: 'SLOW_PAYER_6' as StatusEnum,
    Cutoff7: 'CUTOFF_7' as StatusEnum,
    Preentered89: 'PREENTERED_89' as StatusEnum,
    Approved90: 'APPROVED_90' as StatusEnum,
    LegalRecovery99: 'LEGAL_RECOVERY_99' as StatusEnum,
  };
  export type SexEnum = 'FEMALE_F' | 'MALE_M' | 'UNSPECIFIED_Z';
  export const SexEnum = {
    FemaleF: 'FEMALE_F' as SexEnum,
    MaleM: 'MALE_M' as SexEnum,
    UnspecifiedZ: 'UNSPECIFIED_Z' as SexEnum,
  };
  export type SpecificationEnum =
    | 'NONE_0'
    | 'SINGLE_PERSON_1'
    | 'GROUP_OF_PERSON_2'
    | 'COMPANY_3'
    | 'INTERNAL_COMP_9';
  export const SpecificationEnum = {
    None0: 'NONE_0' as SpecificationEnum,
    SinglePerson1: 'SINGLE_PERSON_1' as SpecificationEnum,
    GroupOfPerson2: 'GROUP_OF_PERSON_2' as SpecificationEnum,
    Company3: 'COMPANY_3' as SpecificationEnum,
    InternalComp9: 'INTERNAL_COMP_9' as SpecificationEnum,
  };
  export type GiroTypeEnum = 'NOTE_0' | 'BANK_1' | 'POST_2';
  export const GiroTypeEnum = {
    Note0: 'NOTE_0' as GiroTypeEnum,
    Bank1: 'BANK_1' as GiroTypeEnum,
    Post2: 'POST_2' as GiroTypeEnum,
  };
  export type NoteBreakUpEnum = 'ASSEMBLED_0' | 'SPLIT_NEWOLD_1';
  export const NoteBreakUpEnum = {
    Assembled0: 'ASSEMBLED_0' as NoteBreakUpEnum,
    SplitNewold1: 'SPLIT_NEWOLD_1' as NoteBreakUpEnum,
  };
  export type InstalmentMethodEnum = 'NORMAL_0' | '_9125D_1' | 'EXACT_DAYS_2';
  export const InstalmentMethodEnum = {
    Normal0: 'NORMAL_0' as InstalmentMethodEnum,
    _9125D1: '_9125D_1' as InstalmentMethodEnum,
    ExactDays2: 'EXACT_DAYS_2' as InstalmentMethodEnum,
  };
  export type NoteTypeEnum =
    | 'MARINE_1_1_0'
    | 'CARGO_1'
    | 'AVIATION_2'
    | 'MARINE_2_1_3'
    | 'CLUB_4'
    | 'MARINE_4_1_5'
    | 'HI_6'
    | 'FEE_NON_MARINE_7'
    | 'AGENTNOTA_ATL_T_8';
  export const NoteTypeEnum = {
    Marine110: 'MARINE_1_1_0' as NoteTypeEnum,
    Cargo1: 'CARGO_1' as NoteTypeEnum,
    Aviation2: 'AVIATION_2' as NoteTypeEnum,
    Marine213: 'MARINE_2_1_3' as NoteTypeEnum,
    Club4: 'CLUB_4' as NoteTypeEnum,
    Marine415: 'MARINE_4_1_5' as NoteTypeEnum,
    Hi6: 'HI_6' as NoteTypeEnum,
    FeeNonMarine7: 'FEE_NON_MARINE_7' as NoteTypeEnum,
    AgentnotaAtlT8: 'AGENTNOTA_ATL_T_8' as NoteTypeEnum,
  };
  export type NoteSortEnum = 'ONLY_CUSTOMER_0' | 'PER_OBJECT_1' | 'OTHER_2';
  export const NoteSortEnum = {
    OnlyCustomer0: 'ONLY_CUSTOMER_0' as NoteSortEnum,
    PerObject1: 'PER_OBJECT_1' as NoteSortEnum,
    Other2: 'OTHER_2' as NoteSortEnum,
  };
  export type StopDunningEnum =
    | 'NOT_SET_0'
    | 'RESPIT_TO_DATE_1'
    | 'STOP_ACC_DUNCO_2';
  export const StopDunningEnum = {
    NotSet0: 'NOT_SET_0' as StopDunningEnum,
    RespitToDate1: 'RESPIT_TO_DATE_1' as StopDunningEnum,
    StopAccDunco2: 'STOP_ACC_DUNCO_2' as StopDunningEnum,
  };
  export type GiroAgreementEnum =
    | 'ACTIVE_A'
    | 'BLOCKED_B'
    | 'CANCELLED_C'
    | 'NONE_Z';
  export const GiroAgreementEnum = {
    ActiveA: 'ACTIVE_A' as GiroAgreementEnum,
    BlockedB: 'BLOCKED_B' as GiroAgreementEnum,
    CancelledC: 'CANCELLED_C' as GiroAgreementEnum,
    NoneZ: 'NONE_Z' as GiroAgreementEnum,
  };
  export type VatIndicatorEnum = 'NO_N' | 'YES_Y' | 'UNKNOWN_Z';
  export const VatIndicatorEnum = {
    NoN: 'NO_N' as VatIndicatorEnum,
    YesY: 'YES_Y' as VatIndicatorEnum,
    UnknownZ: 'UNKNOWN_Z' as VatIndicatorEnum,
  };
  export type DsfAddressCodeEnum =
    | 'VANLIG_BOSATT_0'
    | 'UTENRIKS_1'
    | 'MILIT_R_2'
    | 'SVALBARD_3'
    | 'KLIENTADRESSE_4'
    | 'UTEN_FAST_BO_5'
    | 'SPERRET_STRENG_6'
    | 'SPERRET_FORTRO_7'
    | 'PENDLER_8';
  export const DsfAddressCodeEnum = {
    VanligBosatt0: 'VANLIG_BOSATT_0' as DsfAddressCodeEnum,
    Utenriks1: 'UTENRIKS_1' as DsfAddressCodeEnum,
    MilitR2: 'MILIT_R_2' as DsfAddressCodeEnum,
    Svalbard3: 'SVALBARD_3' as DsfAddressCodeEnum,
    Klientadresse4: 'KLIENTADRESSE_4' as DsfAddressCodeEnum,
    UtenFastBo5: 'UTEN_FAST_BO_5' as DsfAddressCodeEnum,
    SperretStreng6: 'SPERRET_STRENG_6' as DsfAddressCodeEnum,
    SperretFortro7: 'SPERRET_FORTRO_7' as DsfAddressCodeEnum,
    Pendler8: 'PENDLER_8' as DsfAddressCodeEnum,
  };
  export type EinvoiceB2CEnum =
    | 'ACTIVE_A'
    | 'BLOCKED_B'
    | 'CANCELLED_C'
    | 'NONE_Z';
  export const EinvoiceB2CEnum = {
    ActiveA: 'ACTIVE_A' as EinvoiceB2CEnum,
    BlockedB: 'BLOCKED_B' as EinvoiceB2CEnum,
    CancelledC: 'CANCELLED_C' as EinvoiceB2CEnum,
    NoneZ: 'NONE_Z' as EinvoiceB2CEnum,
  };
  export type EinvoiceB2BEnum =
    | 'ACTIVE_A'
    | 'BLOCKED_B'
    | 'CANCELLED_C'
    | 'NONE_Z';
  export const EinvoiceB2BEnum = {
    ActiveA: 'ACTIVE_A' as EinvoiceB2BEnum,
    BlockedB: 'BLOCKED_B' as EinvoiceB2BEnum,
    CancelledC: 'CANCELLED_C' as EinvoiceB2BEnum,
    NoneZ: 'NONE_Z' as EinvoiceB2BEnum,
  };
}
