/**
 * PARIS API
 * The PARIS API is based on a REST achitecture, and is using JSON as data format.<br/>PARIS API is Stateless, the server does not store any state about the client session on the server side. Statelessness ensures that each service consumer request can be treated independently by the service.<br/>Authentication against the API is done using a combination of Basic Authentication and Token based authentication or API-Keys.<br/><br/>©2021 NORIA AS. All Rights Reserved. PARIS is a trademark of <a href=\"http://noria.no/\" target=\"_blank\">NORIA AS</a>.
 *
 * The version of the OpenAPI document: 4.7-202112021325
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
  HttpContext,
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

import { PersonOrganization } from '../model/models';
import { PersonRating } from '../model/models';
import { PersonSubType } from '../model/models';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable({
  providedIn: 'root',
})
export class SystemCodesPersonCodesService {
  protected basePath = 'http://localhost/noria-dev/rest';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  private addToHttpParams(
    httpParams: HttpParams,
    value: any,
    key?: string
  ): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(
    httpParams: HttpParams,
    value?: any,
    key?: string
  ): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach(
          (elem) =>
            (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key))
        );
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(
            key,
            (value as Date).toISOString().substr(0, 10)
          );
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) =>
            (httpParams = this.addToHttpParamsRecursive(
              httpParams,
              value[k],
              key != null ? `${key}.${k}` : k
            ))
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getPersonOrganizations1(
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<Array<PersonOrganization>>;
  public getPersonOrganizations1(
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<HttpResponse<Array<PersonOrganization>>>;
  public getPersonOrganizations1(
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<HttpEvent<Array<PersonOrganization>>>;
  public getPersonOrganizations1(
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<any> {
    let localVarHeaders = this.defaultHeaders;

    let localVarCredential: string | undefined;
    // authentication (Authorization) required
    localVarCredential = this.configuration.lookupCredential('Authorization');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set(
        'Authorization',
        localVarCredential
      );
    }

    // authentication (paris-api-key) required
    localVarCredential = this.configuration.lookupCredential('paris-api-key');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set(
        'paris-api-key',
        localVarCredential
      );
    }

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['*/*'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' = 'json';
    if (
      localVarHttpHeaderAcceptSelected &&
      localVarHttpHeaderAcceptSelected.startsWith('text')
    ) {
      responseType_ = 'text';
    }

    return this.httpClient.get<Array<PersonOrganization>>(
      `${this.configuration.basePath}/systemcodes/personcodes/organizations`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getPersonRatings1(
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<Array<PersonRating>>;
  public getPersonRatings1(
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<HttpResponse<Array<PersonRating>>>;
  public getPersonRatings1(
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<HttpEvent<Array<PersonRating>>>;
  public getPersonRatings1(
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<any> {
    let localVarHeaders = this.defaultHeaders;

    let localVarCredential: string | undefined;
    // authentication (Authorization) required
    localVarCredential = this.configuration.lookupCredential('Authorization');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set(
        'Authorization',
        localVarCredential
      );
    }

    // authentication (paris-api-key) required
    localVarCredential = this.configuration.lookupCredential('paris-api-key');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set(
        'paris-api-key',
        localVarCredential
      );
    }

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['*/*'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' = 'json';
    if (
      localVarHttpHeaderAcceptSelected &&
      localVarHttpHeaderAcceptSelected.startsWith('text')
    ) {
      responseType_ = 'text';
    }

    return this.httpClient.get<Array<PersonRating>>(
      `${this.configuration.basePath}/systemcodes/personcodes/ratings`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * @param type
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getPersonSubTypes1(
    type:
      | 'INSURANCE_COMP_1'
      | 'LAWYER_10'
      | 'AVR_ADJUSTER_11'
      | 'RATING_COMP_12'
      | 'MARITIME_AUTHOR_13'
      | 'INSURANCE_BROKE_2'
      | 'OPPOSITE_PARTY_21'
      | 'CLAIM_RECEIVER_22'
      | 'ONE_TIME_VENDOR_23'
      | 'COVER_3'
      | 'QUOTA_SHTREATY_4'
      | 'CUSTOMER_DIR_5'
      | 'EMPLOYEE_51'
      | 'CREW_52'
      | 'ASSOCIATION_55'
      | 'SALES_AGENT_6'
      | 'AGENTOFFICE_61'
      | 'AGENTEMPLOYEE_62'
      | 'SURVEYOR_7'
      | 'MORTGBANK_8'
      | 'ORGANOFFICE_81'
      | 'ORGEMPLOYEE_82'
      | 'CORRESPONDENT_83'
      | 'REGION_85'
      | 'MORTGOFFICE_86'
      | 'INTERIM_1_88'
      | 'MORTGAGEE_CON_9'
      | 'OWN_RETENTION_91'
      | 'CUTOFF_92'
      | 'OWN_COMM_BR_93'
      | 'TECHNICAL_ADDR_94'
      | 'INTERIM_ACCOUNT_95'
      | 'INGOING_VAT_96'
      | 'OUTGOING_VAT_97'
      | 'INTERIM_2_98'
      | 'OTHER_99',
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<Array<PersonSubType>>;
  public getPersonSubTypes1(
    type:
      | 'INSURANCE_COMP_1'
      | 'LAWYER_10'
      | 'AVR_ADJUSTER_11'
      | 'RATING_COMP_12'
      | 'MARITIME_AUTHOR_13'
      | 'INSURANCE_BROKE_2'
      | 'OPPOSITE_PARTY_21'
      | 'CLAIM_RECEIVER_22'
      | 'ONE_TIME_VENDOR_23'
      | 'COVER_3'
      | 'QUOTA_SHTREATY_4'
      | 'CUSTOMER_DIR_5'
      | 'EMPLOYEE_51'
      | 'CREW_52'
      | 'ASSOCIATION_55'
      | 'SALES_AGENT_6'
      | 'AGENTOFFICE_61'
      | 'AGENTEMPLOYEE_62'
      | 'SURVEYOR_7'
      | 'MORTGBANK_8'
      | 'ORGANOFFICE_81'
      | 'ORGEMPLOYEE_82'
      | 'CORRESPONDENT_83'
      | 'REGION_85'
      | 'MORTGOFFICE_86'
      | 'INTERIM_1_88'
      | 'MORTGAGEE_CON_9'
      | 'OWN_RETENTION_91'
      | 'CUTOFF_92'
      | 'OWN_COMM_BR_93'
      | 'TECHNICAL_ADDR_94'
      | 'INTERIM_ACCOUNT_95'
      | 'INGOING_VAT_96'
      | 'OUTGOING_VAT_97'
      | 'INTERIM_2_98'
      | 'OTHER_99',
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<HttpResponse<Array<PersonSubType>>>;
  public getPersonSubTypes1(
    type:
      | 'INSURANCE_COMP_1'
      | 'LAWYER_10'
      | 'AVR_ADJUSTER_11'
      | 'RATING_COMP_12'
      | 'MARITIME_AUTHOR_13'
      | 'INSURANCE_BROKE_2'
      | 'OPPOSITE_PARTY_21'
      | 'CLAIM_RECEIVER_22'
      | 'ONE_TIME_VENDOR_23'
      | 'COVER_3'
      | 'QUOTA_SHTREATY_4'
      | 'CUSTOMER_DIR_5'
      | 'EMPLOYEE_51'
      | 'CREW_52'
      | 'ASSOCIATION_55'
      | 'SALES_AGENT_6'
      | 'AGENTOFFICE_61'
      | 'AGENTEMPLOYEE_62'
      | 'SURVEYOR_7'
      | 'MORTGBANK_8'
      | 'ORGANOFFICE_81'
      | 'ORGEMPLOYEE_82'
      | 'CORRESPONDENT_83'
      | 'REGION_85'
      | 'MORTGOFFICE_86'
      | 'INTERIM_1_88'
      | 'MORTGAGEE_CON_9'
      | 'OWN_RETENTION_91'
      | 'CUTOFF_92'
      | 'OWN_COMM_BR_93'
      | 'TECHNICAL_ADDR_94'
      | 'INTERIM_ACCOUNT_95'
      | 'INGOING_VAT_96'
      | 'OUTGOING_VAT_97'
      | 'INTERIM_2_98'
      | 'OTHER_99',
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<HttpEvent<Array<PersonSubType>>>;
  public getPersonSubTypes1(
    type:
      | 'INSURANCE_COMP_1'
      | 'LAWYER_10'
      | 'AVR_ADJUSTER_11'
      | 'RATING_COMP_12'
      | 'MARITIME_AUTHOR_13'
      | 'INSURANCE_BROKE_2'
      | 'OPPOSITE_PARTY_21'
      | 'CLAIM_RECEIVER_22'
      | 'ONE_TIME_VENDOR_23'
      | 'COVER_3'
      | 'QUOTA_SHTREATY_4'
      | 'CUSTOMER_DIR_5'
      | 'EMPLOYEE_51'
      | 'CREW_52'
      | 'ASSOCIATION_55'
      | 'SALES_AGENT_6'
      | 'AGENTOFFICE_61'
      | 'AGENTEMPLOYEE_62'
      | 'SURVEYOR_7'
      | 'MORTGBANK_8'
      | 'ORGANOFFICE_81'
      | 'ORGEMPLOYEE_82'
      | 'CORRESPONDENT_83'
      | 'REGION_85'
      | 'MORTGOFFICE_86'
      | 'INTERIM_1_88'
      | 'MORTGAGEE_CON_9'
      | 'OWN_RETENTION_91'
      | 'CUTOFF_92'
      | 'OWN_COMM_BR_93'
      | 'TECHNICAL_ADDR_94'
      | 'INTERIM_ACCOUNT_95'
      | 'INGOING_VAT_96'
      | 'OUTGOING_VAT_97'
      | 'INTERIM_2_98'
      | 'OTHER_99',
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: '*/*'; context?: HttpContext }
  ): Observable<any> {
    if (type === null || type === undefined) {
      throw new Error(
        'Required parameter type was null or undefined when calling getPersonSubTypes1.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarCredential: string | undefined;
    // authentication (Authorization) required
    localVarCredential = this.configuration.lookupCredential('Authorization');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set(
        'Authorization',
        localVarCredential
      );
    }

    // authentication (paris-api-key) required
    localVarCredential = this.configuration.lookupCredential('paris-api-key');
    if (localVarCredential) {
      localVarHeaders = localVarHeaders.set(
        'paris-api-key',
        localVarCredential
      );
    }

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['*/*'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' = 'json';
    if (
      localVarHttpHeaderAcceptSelected &&
      localVarHttpHeaderAcceptSelected.startsWith('text')
    ) {
      responseType_ = 'text';
    }

    return this.httpClient.get<Array<PersonSubType>>(
      `${
        this.configuration.basePath
      }/systemcodes/personcodes/subtypes/${encodeURIComponent(String(type))}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
